#!/usr/bin/env sh

# quick script that retrieves the peers from the fang server, and updates
# the local list, with the intention of punching holes through the NAT
# it requires the wireguard interface to be up

set -e

if [ ${#} -ne 3 ]; then
	echo "check your arguments: ${0} <wg interface> <fang server ip> <fang server port>"
	exit 1
fi

wg addconf "${1}" <(socat "TCP:${2}:${3}",connect-timeout=2 -)
