#!/usr/bin/env sh

# quick script that retrieves the peers from the fang server, and updates
# the local list, with the intention of punching holes through the NAT
# it requires the wireguard interface to be up

set -e

if [ ${#} -ne 3 ]; then
	echo "check your arguments: ${0} <wg interface> <fang server ip> <fang server port>"
	exit 1
fi

TIMEOUT=2
local_interface="${1}"
fang_server_ip="${2}"
fang_server_port="${3}"

wg addconf "${local_interface}" <(socat "TCP:${fang_server_ip}:${fang_server_port}",connect-timeout=${TIMEOUT} -)
