#!/usr/bin/env sh

# this is a very crude way to serve wg peers info over TCP

set -e

if [ ${#} -ne 3 ]; then
	echo "check your arguments: ${0} <wg interface> <listen ip> <listen port>"
	exit 1
fi

socat "tcp-listen:${3},reuseaddr,fork,bind=${2}" "system:wg showconf ${1} | grep -v PrivateKey | grep -v PresharedKey | grep -A1000000 Peer"
