#!/usr/bin/env sh

# this is a very crude way to serve wg peers info over TCP

set -e

if [ ${#} -ne 3 ]; then
	echo "check your arguments: ${0} <wg interface> <listen ip> <listen port>"
	exit 1
fi

interface=${1}
listen_ip=${2}
listen_port=${3}

socat "tcp-listen:${listen_port},reuseaddr,fork,bind=${listen_ip}" "system:wg showconf ${interface} | grep -v PrivateKey | grep -A1000000 Peer"
