#!/usr/bin/env sh

# this is a very crude way to serve wg info over HTTP
# the script will call itself

router() {
	req=$(awk 'BEGIN{RS="\r\n\r\n"} {print; exit}') # read request from stdin until empty lines
	req_path=$(echo "${req}" | grep 'GET' | cut -d' ' -f2)

	printf "HTTP/1.0 200\r\n\r\n"

	case "${req_path}" in
	'/peers')
		interface=$(echo "${req}" | grep interface | awk -F ': ' '{print $2}')
		wg showconf "${interface}" | grep -v 'PrivateKey' | grep -A1000000 "\[Peer\]"
		;;
	*)
		echo "invalid path"
		;;
	esac
}

if [ "${INSIDE_SOCAT_SERVER}" = "inside" ]; then
	router
else
	if [ ${#} -ne 2 ]; then
		echo "check your arguments: ${0} <bind interface name> <server port>"
		exit 1
	fi

	interface=${1}
	port=${2}

	export INSIDE_SOCAT_SERVER=inside
	socat TCP-LISTEN:"${port}",reuseaddr,fork,INTERFACE="${interface}" system:"${0}"
fi
